name: Build Flutter APK (Shabkati WiFi – SalemForNet)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate launcher icons (optional)
        run: dart run flutter_launcher_icons

      - name: Analyze (optional)
        run: flutter analyze

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Build APK (release, split per abi)
        run: flutter build apk --release --split-per-abi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ShabkatiWiFi-APKs
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
